### ISSUE TITLE
Mind if I grab this?

### ISSUE THREAD

**Issue by city41** [socram8888/JNesG#2]
Wow, thank you for archiving this! I wrote this over a decade ago when I was still in school (you can see my college email address in About.java). I'm amazed you found it and amazed you bothered to save it. Thanks!

Would it be ok if I host this on my github account?

**Comment by socram8888** [comment]
Sure, it's yours, go ahead!

**Comment by city41** [comment]
thanks man. I found the src on a CD, so created a repo here: https://github.com/city41/jnesg
